### ISSUE TITLE
Support Rust verification in SAW via `crucible-mir`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1859]
This issue tracks the long-term goal of being able to verify Rust code by leveraging the [`mir-json`](https://github.com/GaloisInc/mir-json) tool to compile Rust code to `.mir` files, which can in turn be ingested by SAW. These `.mir` files then can be symbolically simulated using the `crucible-mir` library, which was recently [split out of `crux-mir`](https://github.com/GaloisInc/crucible/pull/1066) to avoid having SAW incur a Crux dependency.

This is a fairly large undertaking, and as such, the work needed to add SAW support for Rust/MIR will likely be spread out over multiple PRs. Off of the top of my head, here are various tasks that will need to be done:

* [x] A `mir-json` command to produce MIR JSON files suitable for SAW's needs (see https://github.com/GaloisInc/mir-json/issues/39)
* [x] A command to load MIR files from disk (`mir_load_module`) (see https://github.com/GaloisInc/saw-script/pull/1863)
* [x] Update to a more recent Rust nightly. This will require corresponding changes in downstream submodules:
  
  * `mir-json`:
    * GaloisInc/mir-json#22
    * GaloisInc/mir-json#31
    * GaloisInc/mir-json#32
    *  GaloisInc/mir-json#47
    * https://github.com/GaloisInc/mir-json/pull/49
  * `crucible`:
    * GaloisInc/crucible#1050
    * GaloisInc/crucible#1059
    * https://github.com/GaloisInc/crucible/pull/1096

   As well as `saw-script` itself: https://github.com/GaloisInc/saw-script/pull/1891
* [x] Come up with an answer to the "polymorphism problem", i.e., https://github.com/GaloisInc/mir-json/issues/52
* [x] A command to verify MIR files against a SAW specification (`mir_verify`). In turn, this will require:
  * [x] A `MIRSetup` monad for writing SAW specifications about MIR
  * [x] A `MIRSpec` type, which `mir_verify` will return
  * [x] A `mir_execute_func` command for specifying the parameters of the function
  * [x] A `mir_return` command for specifying the return value of a function
  * [x] Combinators for declaring `MIRType`s
  * [x] Combinators for specifying how arguments are allocated (e.g., `mir_points_to`, `mir_alloc`, and `mir_alloc_mut`)
    * [x] Depends on https://github.com/GaloisInc/crucible/issues/1105 / https://github.com/GaloisInc/crucible/pull/1106, which tracks the idea of refactoring the `crucible-mir` memory model to make it easier to use from SAW
  * [x] A `mir_term` function for converting a `Term` to a `MIRTerm`
  * [x] A `mir_fresh_var` command for creating fresh symbolic values
  * [x] `mir_precond`, `mir_postcond`, and `mir_assert` commands for asserting pre- and post-conditions in a specification
  
  I've split up this work into multiple PRs:
  * https://github.com/GaloisInc/saw-script/pull/1904
  * #1916
* [x] `mir_fresh_cryptol_var` (#1970)
* [x] Ghost state (issue: #1929; PR: #1958)
* [x] A `mir_fresh_expanded_val` command, similar to `llvm_fresh_expanded_val` (#1955)
* [x] Commands for initializing MIR constants à la `llvm_global`/`llvm_global_initializer` (#1941)
  * [x] Requires https://github.com/GaloisInc/mir-json/issues/55 / https://github.com/GaloisInc/mir-json/issues/56 first
* [x] A `mir_unsafe_assume_spec` command for assumed SAW specifications (#1959)
* [x] Combinators for working with compound types such as:
  * [x] Arrays (`mir_array_value`). See #1925. 
  * [x] `struct`s (`mir_struct_value`). See #1931.
  * [x] Slices (e.g., `mir_slice_value` and `mir_slice_range_value`) (#1948)
  * [x] Tuples (`mir_tuple_value`) See #1934.
    * [x] Requires https://github.com/GaloisInc/crucible/pull/1107 first
  
  These require https://github.com/GaloisInc/saw-script/issues/1914 first.
* [x] Support for Rust `enum` types in SAW (e.g., `mir_variant_value`) (#1991)
* [x] Add a tutorial about how to verify Rust code using SAW (#1939)  

Nice to have, but not essential for a first cut:

* Update the SAW bindists to include a `mir-json`-translated version of the Rust standard library, similar to what `crux-mir` does with [this script](https://github.com/GaloisInc/crucible/blob/b4422dd2f75f5a7310bc038a6ca67a91f3692a42/crux-mir/translate_libs.sh). Also do this in the SAW Docker images. (#1868)
* Run `crux-mir-comp`'s test suite in CI (https://github.com/GaloisInc/saw-script/issues/1887)
* A `mir_cast_to_immut_ref` function for casting mutable refefences to immutable ones (#1954)
* Reject duplicate `mir_points_to` statements in preconditions (#1956)
* Mark `Freeze` statics as mutable (#1957)
* A `mir_fresh_ref` command, similar to `llvm_fresh_pointer`. (We would also want to implement `mir_fresh_expanded_value` such that it calls `mir_fresh_ref` under the hood to create fresh reference values.) (#1975)
* A `mir_equal` command, similar to `llvm_equal` (#1998)
* Support for the `&str` type (#1997)
* `mir_ref_of`/`mir_ref_mut_of` commands for taking a reference to a value, similar to Rust's `&`/`&mut` operators. (#1999)
* A `mir_elem` command for referencing elements of compound types, and a `mir_field` command for referencing fields of `struct`s (#1983)
* SAW options for configuring the behavior of the `?assertFalseOnError` and `?printCrucible` implicit parameters (https://github.com/GaloisInc/crucible/issues/1080)

**Comment by RyanGlScott** [comment]
We have now implemented enough MIR-related functionality to write interesting SAW proofs involving Rust code. As such, I think this issue has outlived its usefulness, so I will close it. I have opened separate issues for the remaining tasks in the "nice to have" category, and I will tag related issues with the `crucible/mir` tag going forward.
